jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run lint
      - run: npm test

  release:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run semantic-release

orbs:
  node: circleci/node@1.1
version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - build
